language: node_js
node_js:
  - 12
before_install:
  - echo "//familysearch.jfrog.io/familysearch/api/npm/fs-npm-prod-virtual/:_authToken=${NPM_PUBLISH_TOKEN}" >> .npmrc
  - echo "@fs:registry=https://familysearch.jfrog.io/familysearch/api/npm/fs-npm-prod-virtual/" >> .npmrc
deploy:
  provider: npm
  skip_cleanup: true
  email: "dl-fh-eng-frontier@groups.ldschurch.org"
  api_key: "$NPM_PUBLISH_TOKEN"
  on:
    branch: artifactory-publish
